# Generated by Django 4.0.2 on 2022-02-17 07:30

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='toggl_api_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
