# Generated by Django 4.0.2 on 2022-02-18 09:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_toggl_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='workspace_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
